# Generated by Django 4.2.2 on 2023-08-18 18:05

from django.db import migrations
from faker import Faker
from polls.tests.factories.question import QuestionFactory

faker = Faker()


def load_data(apps, schema_editor):

    for i in range(100):
        QuestionFactory.create(question_text=faker.sentence(),
                               days=faker.random_int(min=1, max=1000))


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
